### ISSUE TITLE
eac modules controller revision

### ISSUE THREAD

**Issue by newwby** [newwby/ddat-gpf.eac_modules#42]
### TODO
- [ ] Controller as an extended resource class
- [ ] Controllers are intialised as variants on the class they control
  - [ ] with init structure (arg_owner: Node2D, arg_binds: Dictionary) where binds call globalFunc.multiset on the new controller
- [ ]
